version: "3.8"
services:
  web:
    image: waftring/overlayexample:srv
    ports:
      - target: 80
        published: 9001
        protocol: tcp
    deploy:
      endpoint_mode: vip

  api:
    image: waftring/overlayexample:api
    ports:
      - target: 80
        published: 9000
        protocol: tcp
    deploy:
      endpoint_mode: vip
   
